{{- if and .Values.monitoring.enabled .Values.monitoring.alloy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-alloy
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "alloy") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-alloy
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "alloy") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-alloy
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "alloy") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "evtivity-csms.fullname" . }}-alloy
subjects:
  - kind: ServiceAccount
    name: {{ include "evtivity-csms.fullname" . }}-alloy
    namespace: {{ .Release.Namespace }}
{{- end }}
