{{- if not .Values.appSettings.sensitive.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-app-settings-sensitive
  labels:
    {{- include "evtivity-csms.labels" . | nindent 4 }}
type: Opaque
stringData:
  sensitive-settings.json: |
    {{- $s := dict }}
    {{- if .Values.appSettings.sensitive.smtpPassword }}
    {{- $_ := set $s "smtp.password" .Values.appSettings.sensitive.smtpPassword }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.ftpPassword }}
    {{- $_ := set $s "ftp.password" .Values.appSettings.sensitive.ftpPassword }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.twilioAccountSid }}
    {{- $_ := set $s "twilio.accountSid" .Values.appSettings.sensitive.twilioAccountSid }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.twilioAuthToken }}
    {{- $_ := set $s "twilio.authToken" .Values.appSettings.sensitive.twilioAuthToken }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.twilioFromNumber }}
    {{- $_ := set $s "twilio.fromNumber" .Values.appSettings.sensitive.twilioFromNumber }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.s3AccessKeyId }}
    {{- $_ := set $s "s3.accessKeyIdEnc" .Values.appSettings.sensitive.s3AccessKeyId }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.s3SecretAccessKey }}
    {{- $_ := set $s "s3.secretAccessKeyEnc" .Values.appSettings.sensitive.s3SecretAccessKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.stripeSecretKey }}
    {{- $_ := set $s "stripe.secretKeyEnc" .Values.appSettings.sensitive.stripeSecretKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.stripePublishableKey }}
    {{- $_ := set $s "stripe.publishableKey" .Values.appSettings.sensitive.stripePublishableKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.recaptchaSiteKey }}
    {{- $_ := set $s "security.recaptcha.siteKey" .Values.appSettings.sensitive.recaptchaSiteKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.recaptchaSecretKey }}
    {{- $_ := set $s "security.recaptcha.secretKeyEnc" .Values.appSettings.sensitive.recaptchaSecretKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.googleMapsApiKey }}
    {{- $_ := set $s "googleMaps.apiKey" .Values.appSettings.sensitive.googleMapsApiKey }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.pncHubjectBaseUrl }}
    {{- $_ := set $s "pnc.hubject.baseUrl" .Values.appSettings.sensitive.pncHubjectBaseUrl }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.pncHubjectTokenUrl }}
    {{- $_ := set $s "pnc.hubject.tokenUrl" .Values.appSettings.sensitive.pncHubjectTokenUrl }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.pncHubjectClientId }}
    {{- $_ := set $s "pnc.hubject.clientId" .Values.appSettings.sensitive.pncHubjectClientId }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.pncHubjectClientSecret }}
    {{- $_ := set $s "pnc.hubject.clientSecretEnc" .Values.appSettings.sensitive.pncHubjectClientSecret }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.marketingGtagPortal }}
    {{- $_ := set $s "marketing.gtagPortal" .Values.appSettings.sensitive.marketingGtagPortal }}
    {{- end }}
    {{- if .Values.appSettings.sensitive.marketingGtagCsms }}
    {{- $_ := set $s "marketing.gtagCsms" .Values.appSettings.sensitive.marketingGtagCsms }}
    {{- end }}
    {{ $s | toJson }}
{{- end }}
