{{- if and .Values.gatewayAPI.enabled .Values.gatewayAPI.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "evtivity-csms.fullname" . }}
  labels:
    {{- include "evtivity-csms.labels" . | nindent 4 }}
  {{- with .Values.gatewayAPI.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gatewayAPI.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gatewayAPI.gateway.listeners }}
    - name: {{ .name }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      {{- if .tls }}
      tls:
        mode: Terminate
        certificateRefs:
          {{- toYaml .tls.certificateRefs | nindent 10 }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
