{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-grafana-data
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "grafana") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.grafana.storage.size }}
{{- end }}
