{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-grafana
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "grafana") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "evtivity-csms.componentSelectorLabels" (dict "context" . "component" "grafana") | nindent 4 }}
{{- end }}
