{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-grafana-alerting
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "grafana") | nindent 4 }}
data:
  contactpoints.yml: |
    {{- .Files.Get "alerting/contactpoints.yml" | nindent 4 }}
  policies.yml: |
    {{- .Files.Get "alerting/policies.yml" | nindent 4 }}
  rules.yml: |
    {{- .Files.Get "alerting/rules.yml" | nindent 4 }}
{{- end }}
