{{- if .Values.portal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-portal
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "portal") | nindent 4 }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      {{- include "evtivity-csms.componentSelectorLabels" (dict "context" . "component" "portal") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.portal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evtivity-csms.componentSelectorLabels" (dict "context" . "component" "portal") | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: portal
          image: {{ include "evtivity-csms.image" (dict "context" . "component" "portal" "values" .Values.portal) }}
          imagePullPolicy: {{ include "evtivity-csms.imagePullPolicy" . }}
          ports:
            - name: http
              containerPort: {{ .Values.portal.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          {{- with .Values.portal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "evtivity-csms.fullname" . }}-portal-nginx
      {{- with .Values.portal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.portal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
