{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evtivity-csms.fullname" . }}-worker
  labels:
    {{- include "evtivity-csms.componentLabels" (dict "context" . "component" "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "evtivity-csms.componentSelectorLabels" (dict "context" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "evtivity-csms.componentSelectorLabels" (dict "context" . "component" "worker") | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "evtivity-csms.waitForDeps" . | nindent 8 }}
      containers:
        - name: worker
          image: {{ include "evtivity-csms.image" (dict "context" . "component" "worker" "values" .Values.worker) }}
          imagePullPolicy: {{ include "evtivity-csms.imagePullPolicy" . }}
          envFrom:
            - configMapRef:
                name: {{ include "evtivity-csms.configMapName" . }}
            - secretRef:
                name: {{ include "evtivity-csms.secretName" . }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
